# Generated by Django 3.0.5 on 2022-06-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachersubject',
            fields=[
                ('subject_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=100)),
                ('subject_desc', models.CharField(blank=True, max_length=250)),
                ('s_genre', models.CharField(blank=True, max_length=100)),
                ('s_pic', models.FileField(blank=True, upload_to='books')),
            ],
            options={
                'db_table': 'teachersubject',
            },
        ),
    ]
