# Generated by Django 4.0 on 2022-07-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teachersubject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachersubject',
        ),
    ]
