# Generated by Django 4.0 on 2022-06-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('std_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('content', models.FileField(blank=True, upload_to='image')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
