from turtle import reset
from django.urls import path
from student import views 


urlpatterns = [
    path('',views.studentdashboard,name="studentdashboard"),
    path('studentregister',views.register, name="studentregister"),
    path('studentlogin',views.studentlogin,name="studentlogin"),
    path('logout',views.logout,name='logout'),
    path('studentprofile/<int:s_id>',views.studentprofile,name='studentprofile'),
    path('getanswer',views.getanswer,name='getanswer'),
    path('profileupdate/<int:s_id>',views.profileupdate,name="profileupdate"),
    path('class6', views.class6, name='class6'),
    path('class7', views.class7, name='class7'),
    path('class8', views.class8, name='class8'),
    path('class9', views.class9, name='class9'),
    path('class10', views.class10, name='class10'),
    path('class6science', views.class6science, name='class6science'),
    path('class7science', views.class7science, name='class7science'),
    path('class8science', views.class8science, name='class8science'),
    path('class9science', views.class9science, name='class9science'),
    path('class10science', views.class10science, name='class10science'),
    path('class6english', views.class6english, name='class6english'),
    path('class7english', views.class7english, name='class7english'),
    path('class8english', views.class8english, name='class8english'),
    path('class9english', views.class9english, name='class9english'),
    path('class10english', views.class10english, name='class10english'),
    path('class6computer', views.class6computer, name='class6computer'),
    path('class7computer', views.class7computer, name='class7computer'),
    path('class8computer', views.class8computer, name='class8computer'),
    path('class9computer', views.class9computer, name='class9computer'),
    path('class10computer', views.class10computer, name='class10computer'),
    path('class6math', views.class6math, name='class6math'),
    path('class7math', views.class7math, name='class7math'),
    path('class8math', views.class8math, name='class8math'),
    path('class9math', views.class9math, name='class9math'),
    path('class10math', views.class10math, name='class10math'),
    path('class6social', views.class6social, name='class6social'),
    path('class7social', views.class7social, name='class7social'),
    path('class8social', views.class8social, name='class8social'),
    path('class9social', views.class9social, name='class9social'),
    path('class10social', views.class10social, name='class10social'),
    path('class7account', views.class7account, name='class7account'),
    path('class9account', views.class9account, name='class9account'),
    path('class10account', views.class10account, name='class10account'),
    path('questionanswer', views.questionanswer, name='questionanswer'),
    path('question', views.question, name='question'),
    path('ticket',views.ticket, name='ticket'),
    path('clicklink/<uidb64>/<token>', views.clicklink, name='clicklink'),
    path('student/resetpassword/<int:pk>', views.reset_password, name="resetpassword"),
    path('student/enteremail', views.enter_email, name='enteremail')
]