# Generated by Django 4.0 on 2022-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='customer_password',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_email',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stuent_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
