# Generated by Django 4.0 on 2022-05-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_customer_password_student_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='student_id',
        ),
    ]
