<<<<<<< HEAD
# Generated by Django 4.0 on 2022-06-05 05:58
=======
# Generated by Django 4.0 on 2022-06-05 05:42
>>>>>>> c163024aba3038eb84a3109dd5345932d92f0255

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(blank=True, upload_to='image'),
        ),
    ]
