# Generated by Django 3.0.5 on 2022-06-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_image'),
        ('student', '0003_auto_20220605_0558'),
    ]

    operations = [
    ]
