# Generated by Django 4.0 on 2022-06-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
