# Generated by Django 4.0 on 2022-06-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alladmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_username',
            new_name='username',
        ),
    ]
